test: Cache Babel output (#5539)
This caches Babel's transpiler output for reuse, and should speed up all
test runs in theory, but the effect is most noticeable on local test
runs.

This uses a fork of karma-babel-preprocessor, which contains
https://github.com/babel/karma-babel-preprocessor/pull/77. If/when that
PR is merged, we can move back to the upstream module.

Local runs will start faster because only modified source files will be
re-processed through Babel when the tests start up.

In the Selenium workflow, Babel output and node_modules will both be
computed by the singular build-shaka job, stored, and then reused by all
the Selenium lab matrix jobs.

On my workstation (3.3 GHz cores, 32GB RAM, spinning platter disk), I
see tests start about ~60 seconds faster. In the lab (2.1-4.7 GHz cores,
64GB RAM, solid-state disk), I see tests start about ~10 seconds faster.

diff --git a/.github/workflows/selenium-lab-tests.yaml b/.github/workflows/selenium-lab-tests.yaml
--- a/.github/workflows/selenium-lab-tests.yaml
+++ b/.github/workflows/selenium-lab-tests.yaml
@@ -148,6 +148,30 @@ jobs:
       - name: Build Player
         run: python3 build/all.py
 
+      - name: Preprocess with Babel
+        run: |
+          # Run the test preprocessor without running the actual tests.
+          # This lets us cache Babel's output and run it only once.
+          # Ignore the exit code, since you get an error code if the filter
+          # excludes all tests.
+          ./build/test.py \
+              --use-xvfb --browsers Chrome \
+              --filter ThisFilterMatchesNoTests || true
+
+      - name: Cache dependencies
+        uses: actions/cache@v3
+        id: npm-cache
+        with:
+          path: node_modules/
+          key: node-${{ hashFiles('package-lock.json') }}
+
+      - name: Cache Babel output
+        uses: actions/cache@v3
+        id: babel-cache
+        with:
+          path: .babel-cache
+          key: babel-${{ hashFiles('*.js', 'demo/**.js', 'lib/**.js', 'ui/**.js', 'test/**.js', 'third_party/**.js') }}
+
       - name: Store Player build
         uses: actions/upload-artifact@v3
         with:
@@ -206,6 +230,17 @@ jobs:
         with:
           path: node_modules/
           key: node-${{ hashFiles('package-lock.json') }}
+          fail-on-cache-miss: true  # Cached by the build-shaka job above
+          enableCrossOsArchive: true  # Share archives from Linux to Windows
+
+      - name: Cache Babel output
+        uses: actions/cache@v3
+        id: babel-cache
+        with:
+          path: .babel-cache
+          key: babel-${{ hashFiles('*.js', 'demo/**.js', 'lib/**.js', 'ui/**.js', 'test/**.js', 'third_party/**.js') }}
+          fail-on-cache-miss: true  # Cached by the build-shaka job above
+          enableCrossOsArchive: true  # Share archives from Linux to Windows
 
       - name: Install dependencies
         if: steps.npm-cache.outputs.cache-hit != 'true'
